### MyGarden GET for findAll *pass*

GET /api/my-garden HTTP/1.1
Host: localhost:8080

### MyGarden GET for findById *pass*

GET /api/my-garden/1 HTTP/1.1
Host: localhost:8080

### MyGarden GET for findById *fail* by invalid myGardenId

GET /api/my-garden/100 HTTP/1.1
Host: localhost:8080

### MyGarden GET for findById *fail* by invalid myGardenId

GET /api/my-garden/-1 HTTP/1.1
Host: localhost:8080

### MyGarden POST *pass*

POST /api/my-garden HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdWxlIiwic3ViIjoicmN1Y2NpYSIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIxNjI3Njk0fQ.syvp6QY8rgOi-1cFIp2fHUreTC5qbU4WKNy3Og_8vJk

{
    "gardenName": "Rachel",
    "userId": 3,
    "bio": "testing testing",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden POST *fail* null myGarden

POST /api/my-garden HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{

}

### MyGarden POST *fail* null gardenName

POST /api/my-garden HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "gardenName": null,
    "userId": 3,
    "bio": "testing testing",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden POST *fail* blank gardenName

POST /api/my-garden HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "gardenName": " ",
    "userId": 3,
    "bio": "testing testing",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden POST *fail* 0 userId

POST /api/my-garden HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "gardenName": "Rachel",
    "userId": 0,
    "bio": "testing testing",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden PUT *pass*

PUT /api/my-garden/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "myGardenId": 2,
    "gardenName": "Rachel",
    "userId": 3,
    "bio": "wowie wow",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden PUT *fail* null myGarden

PUT /api/my-garden/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    
}

### MyGarden PUT *fail* invalid id

PUT /api/my-garden/0 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "myGardenId": 0,
    "gardenName": "Rachel",
    "userId": 3,
    "bio": "wowie wow",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden PUT *fail* null gardenName

PUT /api/my-garden/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "myGardenId": 2,
    "gardenName": null,
    "userId": 3,
    "bio": "wowie wow",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden PUT *fail* null gardenName

PUT /api/my-garden/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "myGardenId": 2,
    "gardenName": " ",
    "userId": 3,
    "bio": "wowie wow",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden PUT *fail* 0 userId

PUT /api/my-garden/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "myGardenId": 2,
    "gardenName": " ",
    "userId": 0,
    "bio": "wowie wow",
    "photo": "plant.jpeg",
    "plants": []
}

### MyGarden DELETE *pass*

DELETE /api/my-garden/2 HTTP/1.1
Host: localhost:8080

### MyGarden DELETE *fail* invalid id

DELETE /api/my-garden/0 HTTP/1.1
Host: localhost:8080