### Get all posts
GET /api/post HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Get all from a user
GET /api/post/user/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Get all from an invalid user
GET /api/post/user/100 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Get all from a user
GET /api/post/plant/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Get all from an invalid user
GET /api/post/plant/100 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Get post by id
GET /api/post/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Get post by invalid id
GET /api/post/-1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Add post if valid
POST /api/post HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwbGFudGJhc2UiLCJzdWIiOiJyY3VjY2lhIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MjIwOTIzNzB9.q-L6fR8gRD49EIFU4bQTVv1Sxz1kGShEcnommYvdWhE

{
    "username": "rcuccia",
    "gardenId": 1,
    "caption": " added post test",
    "photo": "test_post.png",
    "datetimePosted": "2021-05-18T06:43:18",
    "likeCount": 0,
    "plantId": 1
}

### Add post if valid
POST /api/post HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "username": "john_smith",
    "gardenId": 1,
    "caption": "Added no plant post",
    "photo": "",
    "datetimePosted": "2021-05-18T06:43:18",
    "likeCount": 0,
    "plantId": 0
}


### Should Not Add Invalid post
POST /api/post HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "username": "john_smith"
    "gardenId": 1,
    "photo": "test_post.png",
    "datetimePosted": "2021-05-18T06:43:18",
    "likeCount": 0,
    "plantId": 1
}


### Should Not Add Invalid Post
POST /api/post HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
}


### Should Not Add on invalid path
POST /api/post/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "username": "john_smith",
    "gardenId": 1,
    "caption": " added post test",
    "photo": "test_post.png",
    "datetimePosted": "2021-05-18T06:43:18",
    "likeCount": 0,
    "plantId": 1
}


### Edit post
PUT /api/post/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "postId": 1,
    "username": "john_smith",
    "gardenId": 1,
    "caption": "test post",
    "photo": "test_post.png",
    "datetimePosted": "2021-05-18T06:43:18",
    "likeCount": 0,
    "plantId": 1
}

### Edit post -- conflict
PUT /api/post/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "postId": 2,
    "planterId": 1,
    "gardenId": 1,
    "caption": " edit post test",
    "photo": "test_post.png",
    "datetimePosted": "2021-05-18T02:43:18",
    "likeCount": 0,
    "plantId": 1
}

### Edit post -- no content
PUT /api/post/a HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "postId": "a"
}

### Delete post (x2 to show 404 when cannot delete invalid id)
DELETE /api/post/1 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000


### Edit post
PUT /api/post/2 HTTP/1.1
Host: localhost:8080
Origin: http://localhost:3000
Content-Type: application/json

{
    "postId": 2,
    "username": "rcuccia",
    "gardenId": 1,
    "caption": "Bonnie",
    "photo": "",
    "datetimePosted": "2021-05-18T02:43:18",
    "likeCount": 5,
    "plantId": 2
}