@url = http://localhost:8080/api/user

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1

###

POST http://localhost:8080/api/location HTTP/1/1
Content-Type: application/json

{
    "role_id": 2,
    "first_name": "George",
    "last_name": "Adams",
    "email": "gadams12@gmail.com"
}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "user_id": 4,
    "role_id": 1,
    "first_name": "Claire",
    "last_name": "O'Lynn",
    "email": "c.olynn@aol.com"
}

###

DELETE {{url}}/4 HTTP/1.1