@url = http://localhost:8080/api/planter

GET {{url}} HTTP/1.1

###

GET {{url}}/rcuccia HTTP/1.1

###

GET {{url}}/100 HTTP/1.1

###

POST http://localhost:8080/api/planter HTTP/1.1
Content-Type: application/json

{
    "roleId": 2,
    "firstName": "George",
    "lastName": "Adams",
    "email": "gadams12@gmail.com"
}

###

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
    "roleId": 2,
    "firstName": "",
    "lastName": "Adams",
    "email": "gadams12@gmail.com"
}

###

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
    "roleId": 2,
    "firstName": "George",
    "lastName": "Adams",
    "email": "gadams12.com"
}

###

POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
    "roleId": 0,
    "firstName": "George",
    "lastName": "Adams",
    "email": "gadams12@gmail.com"
}

###

PUT {{url}}/rcuccia HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwbGFudGJhc2UiLCJzdWIiOiJyY3VjY2lhIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MjE4ODgxMjl9.EHiJFV_HHNAn042msfXXeayyZh3zIYXE05wTPeq1Yxg

{
    "username": "rcuccia",
    "roleId": 2,
    "firstName": "Claire",
    "lastName": "O'Lynn",
    "email": "c.olynn@aol.com"
}

###

###
PUT {{url}}/100 HTTP/1.1
Content-Type: application/json

{
    "userId": 100,
    "roleId": 1,
    "firstName": "Claire",
    "lastName": "O'Lynn",
    "email": "c.olynn@aol.com"
}


###
PUT {{url}}/100 HTTP/1.1
Content-Type: application/json

{
    "userId": 100,
    "roleId": 1,
    "firstName": " ",
    "lastName": " ",
    "email": "c.olynn@aol.com"
}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "userId": 2,
    "roleId": 1,
    "firstName": "Bob",
    "lastName": "Jones",
    "email": "c.olynn.com"
}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "userId": 2,
    "roleId": 1,
    "firstName": "  ",
    "lastName": "Jones",
    "email": "c.olynn@aol.com"
}

###

DELETE {{url}}/ane14 HTTP/1.1

### 
DELETE {{url}}/100 HTTP/1.1
